SELECT MSISDN,
	SUBSCR_ID,
	EMAIL_ADDRESS,
	CASE
		WHEN CAST(AGE AS INT) < 18 THEN '<18'
		WHEN CAST(AGE AS INT) BETWEEN 18 AND 25 THEN '18-25'
		WHEN CAST(AGE AS INT) BETWEEN 26 AND 35 THEN '26-35'
		WHEN CAST(AGE AS INT) BETWEEN 36 AND 45 THEN '36-45'
		ELSE '>45'
	END AS AGE_BAND,
	CASE
		WHEN GENDER = 'male' THEN 'M'
		WHEN GENDER = 'female' THEN 'F'
		ELSE 'U'
	END AS GENDER,
	(SELECT EXTRACT(DAY FROM JOIN_DATE)) AS J_DAY,
	(SELECT EXTRACT(MONTH FROM JOIN_DATE)) AS J_MONTH,
	(SELECT EXTRACT(YEAR FROM JOIN_DATE)) AS J_YEAR,
	POSTAL_SECTOR,
	HANDSET_MODEL,
	HANDSET_MANUFACTURER,
	NEEDS_SEGMENT_NAME,
	SMART_PHONE_IND,
	OPERATING_SYSTEM_NAME,
	LTE_SUBSCR_IND,
	BILL_CYCLE_DAY,
	AVG_3_MTHS_SPEND,
	AVG_3_MTHS_CALLS_USAGE,
	AVG_3_MTHS_SMS_USAGE,
	AVG_3_MTHS_DATA_USAGE,
	AVG_3_MTHS_INTL_CALLS_USAGE,
	AVG_3_MTHS_ROAM_CALLS_USAGE,
	AVG_3_MTHS_ROAM_SMS_USAGE,
	AVG_3_MTHS_ROAM_DATA_USAGE,
	CASE
		WHEN (COALESCE(AVG_3_MTHS_SPEND, 0) +
			COALESCE(AVG_3_MTHS_CALLS_USAGE, 0) +
			COALESCE(AVG_3_MTHS_SMS_USAGE, 0) +
			COALESCE(AVG_3_MTHS_DATA_USAGE, 0) +
			COALESCE(AVG_3_MTHS_INTL_CALLS_USAGE, 0) +
			COALESCE(AVG_3_MTHS_ROAM_CALLS_USAGE, 0) +
			COALESCE(AVG_3_MTHS_ROAM_SMS_USAGE, 0) +
			COALESCE(AVG_3_MTHS_ROAM_DATA_USAGE, 0) > 0) THEN 'Y'
		ELSE 'N'
	END AS AVG_AVAILABLE,
	DATA_BOLTON_IND,
	INSURANCE_BOLTON_IND,
	O2TRAVEL_OPTIN_IND,
	PM_REGISTERED_IND,
	CONNECTION_DT,
	CONTRACT_START_DT,
	CONTRACT_END_DT,
	CONTRACT_TERM_MTHS,
	UPGRADE_DT,
	CUST_TENURE_MTHS,
	PAY_AND_GO_MIGRATED_IND,
	PAY_AND_GO_MIGRATED_DT,
	PORTED_IN_IND,
	PORTED_IN_DT,
	PORTED_IN_FROM_NETWK_NAME,
	DISCONNECTION_DT,
	TARIFF_NAME,
	SIM_ONLY_IND,
	ACQUISITION_CHANNEL_NAME,
	BILLING_SYSTEM_NAME,
	LAST_BILLING_DATE,
	EVENT_DESC,
	CONTACT_EVENT_TYPE_CD,
	EVENT_START_DT,
	CAMPAIGN_CD,
	TEXTS_OPTIN_IND,
	EMAIL_OPTIN_IND,
	PHONE_OPTIN_IND,
	POST_OPTIN_IND,
	ALL_MARKETING_OPTIN_IND
FROM PUBLIC.CUSTOMER_DATA;